version: '3.7'

services:

  swarm-router:
    image: swarm-router:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
      - "1111:1111"
    networks:
      - routing
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 128M
        limits:
          memory: 128M
      mode: global
      restart_policy:
        condition: any

networks:
  routing:
    driver: overlay
    attachable: true
